#!/bin/bash

snap() {
    local vol target
    vol="$(readlink -e "$1")"
    target="$2"

    if [ -e "$target" ]; then
        echo "Target \"$target\" already exists. Exiting."
        exit 1
    fi

    btrfs subvolume snapshot "$vol" "$target" || exit $?

    local realvol="$vol"
    while ! btrfs subvolume list -at "$vol" | tail -n+3 | cut -f5- |
        sed "s/<FS_TREE>\///" | sort | grep -q "^$realvol\$"
    do
        realvol="${realvol#*/}"
    done

    local nested
    readarray -t nested < <(
    btrfs subvolume list -at "$vol" | tail -n+3 | cut -f5- | \
        sed "s/<FS_TREE>\///" | grep "^$realvol/" | sort
    )

    local nvol
    for nvol in "${nested[@]}"; do
        relapath="${nvol#$realvol/}"
        rmdir "$target/$relapath"
        btrfs subvolume snapshot "$vol/$relapath" "$target/$relapath"
    done
}

delete() {
    local vol to_delete=()
    for vol in "$@"; do
        vol="$(realpath "$vol")"

        local realvol="$vol"
        while ! btrfs subvolume list -at "$vol" | tail -n+3 | cut -f5- |
            sed "s/<FS_TREE>\///" | sort | grep -q "^$realvol\$"
        do
            if [[ ! "$realvol" =~ "/" ]]; then
                echo "Subvolume \"$vol\" not found. Exiting."
                exit 1
            fi
            realvol="${realvol#*/}"
        done

        local nested
        readarray -t nested < <(
        btrfs subvolume list -at "$vol" | tail -n+3 | cut -f5- | \
            sed "s/<FS_TREE>\///" | grep "^$realvol/" | sort -r
        )

        local nvol
        for nvol in "${nested[@]}"; do
            to_delete+=("$vol/${nvol#$realvol/}")
            btrfs property set -ts "$vol/${nvol#$realvol/}" ro false
        done

        to_delete+=("$vol")
    done

    btrfs property set -ts "$vol" ro false
    btrfs subvolume delete "${to_delete[@]}"
}

main() {
    local delete

    while true; do
        case "$1" in
            -d)
                shift
                delete=1
                ;;
            *)
                break
                ;;
        esac
    done

    if [ "$delete" ]; then
        delete "$@"
    else
        snap "$@"
    fi
}

main "$@"
